import { SessionProvider } from '@/components/SessionProvider';
import '../app/globals.css';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import { getServerSession } from 'next-auth';
import Login from '@/components/Login';

export const metadata = {
  title: 'Mintable Lite',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  return (
    <html>
      <body>
       <SessionProvider session={session}>
          {!session ? (
              <Login  />
          ):( 
              <div>{children}</div>
          )}
        </SessionProvider> 
      </body>
    </html>
  );
}
